name: featureTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-testers:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v4
         - name: set up php
           uses: shivammathur/setup-php@v2
           with:
             php-version: '8.4.1'
         - name: Install Dependencies 
           run: |
             composer install
             cp .env.example .env
             php artisan key:generate
             php artisan migrate
         - name: Run Feature Tests
           run: ./vendor/bin/phpunit --testsuite=Feature